### ISSUE TITLE
Materials: additional textures

### ISSUE THREAD

**Issue by mrehayden1** [sgillespie/haskell-gltf-loader#10]
As defined here: https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#additional-textures

Also to use normal maps tangents would also be required, so importing tangents would also be helpful. Generating them is probably out of the scope of this project?

**Comment by mrehayden1** [comment]
I've made a start on this here:

https://github.com/sgillespie/haskell-gltf-loader/compare/main...mrehayden1:haskell-gltf-loader:feature/pbr-textures?expand=1

**Comment by mrehayden1** [comment]
![image](https://github.com/sgillespie/haskell-gltf-loader/assets/547652/9f35597e-f039-479e-ad32-4a0c3aa72a9e)

So far normal maps and tangents exported from Blender are working with this branch.

**Comment by mrehayden1** [comment]
![image](https://github.com/sgillespie/haskell-gltf-loader/assets/547652/9fcef4ad-3739-47ee-be02-8447f19dd1cd)

Metallic roughness textures exported from Blender also looking good.

**Comment by sgillespie** [comment]
Completed by #12
