### ISSUE TITLE
Matrices are deocded in row-major order.

### ISSUE THREAD

**Issue by mrehayden1** [sgillespie/haskell-gltf-loader#16]
As per the spec, quoted below.

> 3.6.2.4. Data Alignment
>
>[...]
>
>Accessors of matrix type have data stored in column-major order;

However, the `getMat2`, `getMat3` and `getMat4` decoders read matrix components into the default order of `Linear.Matrix` matrices, which are all stored in row order.

**Comment by sgillespie** [comment]
You're right, I do recall dealing this some time back: https://github.com/sgillespie/seangine/blob/master/lib/Graphics/Seangine/Render/ColumnMajorM44.hs#L1

**Comment by mrehayden1** [comment]
I'm marshalling matrices to OpenGL so I just set the flag accordingly when loading matrices. I don't suppose there's much to be lost from using row major representation as long as you're aware of the convention your graphics library uses.

What do you think?

**Comment by sgillespie** [comment]
> I'm marshalling matrices to OpenGL so I just set the flag accordingly when loading matrices. I don't suppose there's much to be lost from using row major representation as long as you're aware of the convention your graphics library uses.
> 
> What do you think?

Personally, I'd rather be consistent with the GlTF specification

**Comment by mrehayden1** [comment]
Well the only issue with that is we're using M44 etc, a representation that is inconsistent with the specification.

`linear` is very clear about the representation it uses though, so I've not struggled to marshal them into OpenGL correctly so far.
