### ISSUE TITLE
Animation support

### ISSUE THREAD

**Issue by mrehayden1** [sgillespie/haskell-gltf-loader#9]
I'd be very happy to start on this if it suits you.

**Comment by sgillespie** [comment]
Your help would greatly be appreciated (and already is). Be sure to update from main first.

**Comment by mrehayden1** [comment]
Great, and thanks!

Will do, and I'll get my head round nix next.

**Comment by sgillespie** [comment]
Note that nix _should not_ be required to build or test

**Comment by sgillespie** [comment]
Completed by #14
